# Site wide configuration

title: Justin Lee
description: Engineer. Doofus. Pen enthusiast.
logo: twittercard.jpg# 120x120 px default image used for Twitter summary card
teaser: teaser.gif# 400x250 px default teaser image used in image archive grid
locale:
url: http://jwlee.me

# Jekyll configuration
markdown: kramdown
timezone: US/Eastern
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:

  - jekyll-sitemap


# Site owner
owner:
  name: Justin Lee
  email: j@jwlee.me
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: Engineer. Pen enthusiast.
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: pengineered


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
